from django.db import models


class SchemaPactEssNoteNoteProgressNoteNoteBwresultsBw5(models.Model):
    id = models.IntegerField(primary_key=True)
    test_date = models.DateField(null=True, blank=True)
    tests_vl = models.IntegerField(null=True, blank=True)
    tests_cd = models.IntegerField(null=True, blank=True)
    vl = models.IntegerField(null=True, blank=True)
    cd_cdcnt = models.IntegerField(null=True, blank=True)
    cd_cdper = models.IntegerField(null=True, blank=True)
    parent_id = models.IntegerField(null=True, blank=True)
    class Meta:
        db_table = u'schema_pact_ess_note_note_progress_note_note_bwresults_bw_5'

class SchemaPactPactProgressNote2(models.Model):
    id = models.IntegerField(primary_key=True)
    meta_deviceid = models.CharField(max_length=765, blank=True)
    meta_timestart = models.DateTimeField(null=True, blank=True)
    meta_timeend = models.DateTimeField(null=True, blank=True)
    meta_username = models.CharField(max_length=765, blank=True)
    progress_note_meta_chw_id = models.CharField(max_length=765, blank=True)
    meta_uid = models.CharField(max_length=765, blank=True)
    progress_note_case_case_id = models.CharField(max_length=765, blank=True)
    progress_note_case_date_modified = models.DateTimeField(null=True, blank=True)
    progress_note_note_pact_id = models.CharField(max_length=765, blank=True)
    progress_note_note_encounter_date = models.DateField(null=True, blank=True)
    progress_note_note_times_office = models.IntegerField(null=True, blank=True)
    progress_note_note_times_home = models.IntegerField(null=True, blank=True)
    progress_note_note_times_other = models.IntegerField(null=True, blank=True)
    progress_note_note_times_other_location = models.CharField(max_length=765, blank=True)
    progress_note_note_times_accompaniment = models.IntegerField(null=True, blank=True)
    progress_note_note_times_accompaniment_type = models.CharField(max_length=765, blank=True)
    progress_note_note_times_phone = models.IntegerField(null=True, blank=True)
    progress_note_note_times_missed_visit = models.CharField(max_length=765, blank=True)
    progress_note_note_times_discussion = models.IntegerField(null=True, blank=True)
    progress_note_note_times_administrative = models.IntegerField(null=True, blank=True)
    progress_note_note_times_travel = models.IntegerField(null=True, blank=True)
    progress_note_note_discussed_appointments = models.CharField(max_length=765, blank=True)
    progress_note_note_discussed_goals = models.CharField(max_length=765, blank=True)
    progress_note_note_discussed_followup = models.CharField(max_length=765, blank=True)
    progress_note_note_reviewed_cd = models.CharField(max_length=765, blank=True)
    progress_note_note_discussed_qsp = models.CharField(max_length=765, blank=True)
    progress_note_note_pill_check = models.CharField(max_length=765, blank=True)
    progress_note_note_adherence_missed = models.IntegerField(null=True, blank=True)
    progress_note_note_adherence_possible = models.IntegerField(null=True, blank=True)
    progress_note_note_adherence_freetext = models.CharField(max_length=765, blank=True)
    progress_note_note_adherence_self_report = models.CharField(max_length=765, blank=True)
    progress_note_note_conversations_intro_intro_introduction = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_intro_intro_whatshiv = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_intro_intro_whatsimm = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_intro_intro_whatscd = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_intro_intro_whatsvl = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_intro_intro_whatsaids = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_intro_intro_howaids = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_intro_intro_whatsad = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_intro_intro_whatshr = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_pillbox_pillbox_medlist = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_pillbox_pillbox_readpb = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_pillbox_pillbox_fillpb = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_meds_meds_pharmpl = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_meds_meds_refill = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_meds_meds_barriers = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_adherence_adherence_routine = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_adherence_adherence_pillchart = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_adherence_adherence_ditlpill = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_symptoms_symptoms_manage = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_symptoms_symptoms_sideff = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_symptoms_symptoms_action = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_hiv_hiv_trans = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_hiv_hiv_sitesm = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_hiv_hiv_sitesf = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_hiv_hiv_knowcd = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_hiv_hiv_mycd = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_networks_networks_mynetw = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_networks_networks_socialt = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_networks_networks_contact = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_networks_networks_cards = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_strengths_strengths_adhiss = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_strengths_strengths_strenghts = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_maintenance_maintenance_card = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_appointments_appointments_pre = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_appointments_appointments_post = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_sexual_behavior_sb_harmrm = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_sexual_behavior_sb_harmrf = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_sexual_behavior_sb_why = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_substance_use_substance_use_con = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_substance_use_substance_use_cha = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_relationships_relationships_whe = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_relationships_relationships_cha = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_diet_diet_recall = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_diet_diet_resources = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_diet_diet_pyramid = models.IntegerField(null=True, blank=True)
    parent_id = models.IntegerField(null=True, blank=True)
    class Meta:
        db_table = u'schema_pact_pact_progress_note_2'

class SchemaPactPactProgressNote3(models.Model):
    id = models.IntegerField(primary_key=True)
    meta_deviceid = models.CharField(max_length=765, blank=True)
    meta_timestart = models.DateTimeField(null=True, blank=True)
    meta_timeend = models.DateTimeField(null=True, blank=True)
    meta_username = models.CharField(max_length=765, blank=True)
    progress_note_meta_chw_id = models.CharField(max_length=765, blank=True)
    meta_uid = models.CharField(max_length=765, blank=True)
    progress_note_case_case_id = models.CharField(max_length=765, blank=True)
    progress_note_case_date_modified = models.DateTimeField(null=True, blank=True)
    progress_note_note_pact_id = models.CharField(max_length=765, blank=True)
    progress_note_note_encounter_date = models.DateField(null=True, blank=True)
    progress_note_note_times_office = models.IntegerField(null=True, blank=True)
    progress_note_note_times_home = models.IntegerField(null=True, blank=True)
    progress_note_note_times_other = models.IntegerField(null=True, blank=True)
    progress_note_note_times_other_location = models.CharField(max_length=765, blank=True)
    progress_note_note_times_accompaniment = models.IntegerField(null=True, blank=True)
    progress_note_note_times_accompaniment_type = models.CharField(max_length=765, blank=True)
    progress_note_note_times_phone = models.IntegerField(null=True, blank=True)
    progress_note_note_times_missed_visit = models.CharField(max_length=765, blank=True)
    progress_note_note_times_discussion = models.IntegerField(null=True, blank=True)
    progress_note_note_times_administrative = models.IntegerField(null=True, blank=True)
    progress_note_note_times_travel = models.IntegerField(null=True, blank=True)
    progress_note_note_discussed_appointments = models.CharField(max_length=765, blank=True)
    progress_note_note_discussed_goals = models.CharField(max_length=765, blank=True)
    progress_note_note_discussed_followup = models.CharField(max_length=765, blank=True)
    progress_note_note_reviewed_cd = models.CharField(max_length=765, blank=True)
    progress_note_note_discussed_qsp = models.CharField(max_length=765, blank=True)
    progress_note_note_pill_check = models.CharField(max_length=765, blank=True)
    progress_note_note_adherence_missed = models.IntegerField(null=True, blank=True)
    progress_note_note_adherence_possible = models.IntegerField(null=True, blank=True)
    progress_note_note_adherence_freetext = models.CharField(max_length=765, blank=True)
    progress_note_note_adherence_self_report = models.CharField(max_length=765, blank=True)
    progress_note_note_conversations_which_intr = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_which_pill = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_which_meds = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_which_adherence = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_which_symps = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_which_hiv = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_which_netws = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_which_strengths = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_which_maint = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_which_appt = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_which_sex = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_which_subst = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_which_rel = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_which_diet = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_intro_intro_introduction = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_intro_intro_whatshiv = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_intro_intro_whatsimm = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_intro_intro_whatscd = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_intro_intro_whatsvl = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_intro_intro_whatsaids = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_intro_intro_howaids = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_intro_intro_whatsad = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_intro_intro_whatshr = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_pillbox_pillbox_medlist = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_pillbox_pillbox_readpb = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_pillbox_pillbox_fillpb = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_meds_meds_pharmpl = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_meds_meds_refill = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_meds_meds_barriers = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_adherence_adherence_routine = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_adherence_adherence_pillchart = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_adherence_adherence_ditlpill = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_symptoms_symptoms_manage = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_symptoms_symptoms_sideff = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_symptoms_symptoms_action = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_hiv_hiv_trans = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_hiv_hiv_sitesm = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_hiv_hiv_sitesf = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_hiv_hiv_knowcd = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_hiv_hiv_mycd = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_networks_networks_mynetw = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_networks_networks_socialt = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_networks_networks_contact = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_networks_networks_cards = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_strengths_strengths_adhiss = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_strengths_strengths_strenghts = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_maintenance_maintenance_card = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_appointments_appointments_pre = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_appointments_appointments_post = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_sexual_behavior_sb_harmrm = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_sexual_behavior_sb_harmrf = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_sexual_behavior_sb_why = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_substance_use_substance_use_con = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_substance_use_substance_use_cha = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_relationships_relationships_whe = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_relationships_relationships_cha = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_diet_diet_recall = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_diet_diet_resources = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_diet_diet_pyramid = models.IntegerField(null=True, blank=True)
    progress_note_note_memo = models.CharField(max_length=765, blank=True)
    parent_id = models.IntegerField(null=True, blank=True)
    class Meta:
        db_table = u'schema_pact_pact_progress_note_3'

class SchemaPactPactProgressNote4(models.Model):
    id = models.IntegerField(primary_key=True)
    meta_deviceid = models.CharField(max_length=765, blank=True)
    meta_timestart = models.DateTimeField(null=True, blank=True)
    meta_timeend = models.DateTimeField(null=True, blank=True)
    meta_username = models.CharField(max_length=765, blank=True)
    progress_note_meta_chw_id = models.CharField(max_length=765, blank=True)
    meta_uid = models.CharField(max_length=765, blank=True)
    progress_note_case_case_id = models.CharField(max_length=765, blank=True)
    progress_note_case_date_modified = models.DateTimeField(null=True, blank=True)
    progress_note_note_pact_id = models.CharField(max_length=765, blank=True)
    progress_note_note_encounter_date = models.DateField(null=True, blank=True)
    progress_note_note_times_office = models.IntegerField(null=True, blank=True)
    progress_note_note_times_home = models.IntegerField(null=True, blank=True)
    progress_note_note_times_other = models.IntegerField(null=True, blank=True)
    progress_note_note_times_other_location = models.CharField(max_length=765, blank=True)
    progress_note_note_times_accompaniment = models.IntegerField(null=True, blank=True)
    progress_note_note_times_accompaniment_type = models.CharField(max_length=765, blank=True)
    progress_note_note_times_phone = models.IntegerField(null=True, blank=True)
    progress_note_note_times_missed_visit = models.CharField(max_length=765, blank=True)
    progress_note_note_times_discussion = models.IntegerField(null=True, blank=True)
    progress_note_note_times_administrative = models.IntegerField(null=True, blank=True)
    progress_note_note_times_travel = models.IntegerField(null=True, blank=True)
    progress_note_note_discussed_appointments = models.CharField(max_length=765, blank=True)
    progress_note_note_discussed_goals = models.CharField(max_length=765, blank=True)
    progress_note_note_discussed_followup = models.CharField(max_length=765, blank=True)
    progress_note_note_reviewed_cd = models.CharField(max_length=765, blank=True)
    progress_note_note_discussed_qsp = models.CharField(max_length=765, blank=True)
    progress_note_note_adherence_missed = models.IntegerField(null=True, blank=True)
    progress_note_note_adherence_possible = models.IntegerField(null=True, blank=True)
    progress_note_note_adherence_freetext = models.CharField(max_length=765, blank=True)
    progress_note_note_adherence_self_report = models.CharField(max_length=765, blank=True)
    progress_note_note_conversations_which_intr = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_which_pill = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_which_meds = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_which_adherence = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_which_symps = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_which_hiv = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_which_netws = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_which_strengths = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_which_maint = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_which_appt = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_which_sex = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_which_subst = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_which_rel = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_which_diet = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_intro_intro_introduction = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_intro_intro_whatshiv = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_intro_intro_whatsimm = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_intro_intro_whatscd = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_intro_intro_whatsvl = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_intro_intro_whatsaids = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_intro_intro_howaids = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_intro_intro_whatsad = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_intro_intro_whatshr = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_pillbox_pillbox_medlist = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_pillbox_pillbox_readpb = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_pillbox_pillbox_fillpb = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_meds_meds_pharmpl = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_meds_meds_refill = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_meds_meds_barriers = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_adherence_adherence_routine = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_adherence_adherence_pillchart = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_adherence_adherence_ditlpill = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_symptoms_symptoms_manage = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_symptoms_symptoms_sideff = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_symptoms_symptoms_action = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_hiv_hiv_trans = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_hiv_hiv_sitesm = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_hiv_hiv_sitesf = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_hiv_hiv_knowcd = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_hiv_hiv_mycd = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_networks_networks_mynetw = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_networks_networks_socialt = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_networks_networks_contact = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_networks_networks_cards = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_strengths_strengths_adhiss = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_strengths_strengths_strenghts = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_maintenance_maintenance_card = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_appointments_appointments_pre = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_appointments_appointments_post = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_sexual_behavior_sb_harmrm = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_sexual_behavior_sb_harmrf = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_sexual_behavior_sb_why = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_substance_use_substance_use_con = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_substance_use_substance_use_cha = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_relationships_relationships_whe = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_relationships_relationships_cha = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_diet_diet_recall = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_diet_diet_resources = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_diet_diet_pyramid = models.IntegerField(null=True, blank=True)
    progress_note_note_memo = models.CharField(max_length=765, blank=True)
    parent_id = models.IntegerField(null=True, blank=True)
    class Meta:
        db_table = u'schema_pact_pact_progress_note_4'

class SchemaPactPactProgressNote5(models.Model):
    id = models.IntegerField(primary_key=True)
    meta_deviceid = models.CharField(max_length=765, blank=True)
    meta_timestart = models.DateTimeField(null=True, blank=True)
    meta_timeend = models.DateTimeField(null=True, blank=True)
    meta_username = models.CharField(max_length=765, blank=True)
    progress_note_meta_chw_id = models.CharField(max_length=765, blank=True)
    meta_uid = models.CharField(max_length=765, blank=True)
    progress_note_case_case_id = models.CharField(max_length=765, blank=True)
    progress_note_case_date_modified = models.DateTimeField(null=True, blank=True)
    progress_note_note_pact_id = models.CharField(max_length=765, blank=True)
    progress_note_note_encounter_date = models.DateField(null=True, blank=True)
    progress_note_note_times_office = models.IntegerField(null=True, blank=True)
    progress_note_note_times_home = models.IntegerField(null=True, blank=True)
    progress_note_note_times_other = models.IntegerField(null=True, blank=True)
    progress_note_note_times_other_location = models.CharField(max_length=765, blank=True)
    progress_note_note_times_accompaniment = models.IntegerField(null=True, blank=True)
    progress_note_note_times_accompaniment_type = models.CharField(max_length=765, blank=True)
    progress_note_note_times_phone = models.IntegerField(null=True, blank=True)
    progress_note_note_times_missed_visit = models.CharField(max_length=765, blank=True)
    progress_note_note_times_discussion = models.IntegerField(null=True, blank=True)
    progress_note_note_times_administrative = models.IntegerField(null=True, blank=True)
    progress_note_note_times_travel = models.IntegerField(null=True, blank=True)
    progress_note_note_discussed_appointments = models.CharField(max_length=765, blank=True)
    progress_note_note_discussed_goals = models.CharField(max_length=765, blank=True)
    progress_note_note_discussed_followup = models.CharField(max_length=765, blank=True)
    progress_note_note_reviewed_cd = models.CharField(max_length=765, blank=True)
    progress_note_note_discussed_qsp = models.CharField(max_length=765, blank=True)
    progress_note_note_adherence_missed = models.IntegerField(null=True, blank=True)
    progress_note_note_adherence_possible = models.IntegerField(null=True, blank=True)
    progress_note_note_adherence_freetext = models.CharField(max_length=765, blank=True)
    progress_note_note_adherence_self_report = models.CharField(max_length=765, blank=True)
    progress_note_note_conversations_which_intr = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_which_pill = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_which_meds = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_which_adherence = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_which_symps = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_which_hiv = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_which_netws = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_which_strengths = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_which_maint = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_which_appt = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_which_sex = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_which_subst = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_which_rel = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_which_diet = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_intro_intro_introduction = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_intro_intro_whatshiv = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_intro_intro_whatsimm = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_intro_intro_whatscd = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_intro_intro_whatsvl = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_intro_intro_whatsaids = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_intro_intro_howaids = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_intro_intro_whatsad = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_intro_intro_whatshr = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_pillbox_pillbox_medlist = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_pillbox_pillbox_readpb = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_pillbox_pillbox_fillpb = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_meds_meds_pharmpl = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_meds_meds_refill = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_meds_meds_barriers = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_adherence_adherence_routine = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_adherence_adherence_pillchart = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_adherence_adherence_ditlpill = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_symptoms_symptoms_manage = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_symptoms_symptoms_sideff = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_symptoms_symptoms_action = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_hiv_hiv_trans = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_hiv_hiv_sitesm = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_hiv_hiv_sitesf = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_hiv_hiv_knowcd = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_hiv_hiv_mycd = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_networks_networks_mynetw = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_networks_networks_socialt = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_networks_networks_contact = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_networks_networks_cards = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_strengths_strengths_adhiss = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_strengths_strengths_strenghts = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_maintenance_maintenance_card = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_appointments_appointments_pre = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_appointments_appointments_post = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_sexual_behavior_sb_harmrm = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_sexual_behavior_sb_harmrf = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_sexual_behavior_sb_why = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_substance_use_substance_use_con = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_substance_use_substance_use_cha = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_relationships_relationships_whe = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_relationships_relationships_cha = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_diet_diet_recall = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_diet_diet_resources = models.IntegerField(null=True, blank=True)
    progress_note_note_conversations_diet_diet_pyramid = models.IntegerField(null=True, blank=True)
    progress_note_note_memo = models.CharField(max_length=765, blank=True)
    parent_id = models.IntegerField(null=True, blank=True)
    class Meta:
        db_table = u'schema_pact_pact_progress_note_5'

class SchemaPactTeNoteProgressNoteNoteReferralsReferral2(models.Model):
    id = models.IntegerField(primary_key=True)
    ref_type = models.CharField(max_length=765, blank=True)
    ref_date = models.DateField(null=True, blank=True)
    parent_id = models.IntegerField(null=True, blank=True)
    class Meta:
        db_table = u'schema_pact_te_note_progress_note_note_referrals_referral_2'

class SchemaPactTeNoteProgressNoteNoteReferralsReferral3(models.Model):
    id = models.IntegerField(primary_key=True)
    ref_type = models.CharField(max_length=765, blank=True)
    ref_date = models.DateField(null=True, blank=True)
    parent_id = models.IntegerField(null=True, blank=True)
    class Meta:
        db_table = u'schema_pact_te_note_progress_note_note_referrals_referral_3'

class SchemaPactTeNoteProgressNoteNoteReferralsReferral4(models.Model):
    id = models.IntegerField(primary_key=True)
    ref_type = models.CharField(max_length=765, blank=True)
    ref_date = models.DateField(null=True, blank=True)
    parent_id = models.IntegerField(null=True, blank=True)
    class Meta:
        db_table = u'schema_pact_te_note_progress_note_note_referrals_referral_4'

class SchemaPactTeNoteProgressNoteNoteReferralsReferral5(models.Model):
    id = models.IntegerField(primary_key=True)
    ref_type = models.CharField(max_length=765, blank=True)
    ref_date = models.DateField(null=True, blank=True)
    parent_id = models.IntegerField(null=True, blank=True)
    class Meta:
        db_table = u'schema_pact_te_note_progress_note_note_referrals_referral_5'


